language: ruby

cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - jruby-9

script:
  - bundle exec rake

notifications:
  email: false
  webhooks:
    urls:
      - https://uplink-app.herokuapp.com/travis_hooks
